### ISSUE TITLE
Ho to use the output when validating?

### ISSUE THREAD

**Issue by nschoe** [derhuerst/multiselect-prompt#1]
Hi,

I have just copied / pasted the example from the readme, but when running it, the output I get is not the same, and is much less useful:

``` Bash
✔ Which colors do you like? – Space to select. Return to submit.
  red
✔ yellow
✔ green
  blue
✔ black
  white
Submitted with [ { selected: false },
  { selected: true },
  { selected: true },
  { selected: false },
  { selected: true },
  { selected: false } ]

```

As you can see, I get only an array of object with just one field `selected` which is a boolean. I find it much less useful that having the real `value` fields.
Have I missed something?

I have literally copied / pasted the example and am running node version `6.8.0`.

**Comment by derhuerst** [comment]
The readme is misleading, I'm sorry. I should probably document this better.

What you get passed is an object with a `selected` property. The prototype of this object points to another object which actually holds `value`. `console.log()` therefore doesn't show it, but you can access `e.value`.

**Comment by derhuerst** [comment]
Let me know of any other difficulties or gotchas that you come across!

**Comment by nschoe** [comment]
HI and thanks @derhuerst , that's a very fast answer. Thanks!
Hum, I've mot sure I understand what you meant, I've tried to change this line `.on('submit', (v) => console.log('Submitted with', v))` to `.on('submit', (v) => console.log('Submitted with', v.value))` but I get `undefined`.

In your example, when you can use the `.value` property is only in the `.abort` event.

So could you show a piece of code to actually get the result?
Thanks!

**Comment by derhuerst** [comment]
Sure, will double-check and post an example.

**Comment by nschoe** [comment]
Okay thanks, I'm scouting through the code to see if I can spot, but an example will be welcomed.
Thx

**Comment by derhuerst** [comment]
Okay. In fact, the docs were not actually wrong, but misleading.

Both on `abort` and on `submit`, _an array_ of all items will be emitted. Each item (itself) has a `selected` boolean and a `value` property (inside the prototype chain). It looks like this:

``` js
[
  {selected: true} --> {value: 'foo', title: 'foo'},
  {selected: false} --> {value: 'bar', title: 'bar'},
  {selected: true} --> {value: 'baz', title: 'baz'}
]
```

So you can do it like [in the readme](https://github.com/derhuerst/multiselect-prompt/commit/d3f360a35fefc5dcfd1e85cf7b859854710b9de8#diff-0730bb7c2e8f9ea2438b52e419dd86c9R36).

**Comment by nschoe** [comment]
Ho okay, I've just got it now, thanks for the answer and the reactivity!
