### ISSUE TITLE
[Feature Request] - Set max number of choices

### ISSUE THREAD

**Issue by nschoe** [derhuerst/multiselect-prompt#2]
It would be great if one could set the max number of selected item, so one can have prompt to ask 'Choose 2 of these items: '.

**Comment by derhuerst** [comment]
What is supposed to happen it the max nr of choices is reached? Would it `tput bel` because you can't select more? Would it just submit?

**Comment by derhuerst** [comment]
I imagine a configurable function `onMaxChoices` being useful. It could then react like the dev wants.

**Comment by nschoe** [comment]
I'm working on a PR right now. I had two ideas in mind:
- un-select the first items (you know, like a FIFO), but somehow that looks counter-intuitive
- just run the bell and not select the item, seems simple enough

**Comment by derhuerst** [comment]
Closing in favour of #3.
