### ISSUE TITLE
[Feature Request] - Change the prefix

### ISSUE THREAD

**Issue by nschoe** [derhuerst/multiselect-prompt#4]
Hi again (sorry but I really like your library and now that I'm actively using it, I can find some enhancements, hope this is not a problem :-)

When we use the default example on the readme, we get this question:

``` Bash
? Which colors do you like?
```

With the first '?' character in a blue color (at least on my terminal).
I think this should be a good idea to provide the user with a way of modifying this prefix, because, in my case, for instance, I don't really like the colored '?' be fire, I'd rather have nothing (so override it with the empty string).

I'm not sure this is an issue related to `multiselect-prompt`, but rather to the skeleton. I can't find it _now_, but I _know_ that I saw a `.prefix` getter somewhere, and the setter was explicitly implemented as `throw`ing and error.

Why isn't it allowed to change the prefix?

Thx!

**Comment by derhuerst** [comment]
> I _know_ that I saw a `.prefix` getter somewhere, and the setter was explicitly implemented as `throw`ing and error.

Um, actually I can't tell why now. I wrote this a while a ago.

The reason behind the "?" not being changeable is a common visual style among all components that use [`cli-styles`](https://github.com/derhuerst/cli-styles#cli-styles-) and [`prompt-skeleton`](https://github.com/derhuerst/prompt-skeleton#prompt-skeleton). As all of them are a modular, less bloated, less `class`y rewrite of [Inquirer.js](https://github.com/SBoudrias/Inquirer.js), I intend them to have the same look as far as possible.

[`multiselect-prompt` calls `cli-styles.symbol` to get the "?"](https://github.com/derhuerst/multiselect-prompt/blob/f92d823/index.js#L118).

**Comment by nschoe** [comment]
thanks again for being so reactive, indeed it calls `cli-styles`, but I believe [this](https://github.com/derhuerst/cli-styles/blob/master/index.js#L20) is actually pretty easy to configure.
Why use `Object.freeze()`?
Wouldn't it be okay for users to simply change it, smth like:

``` Javascript
const ui = require ('cli-styles')
ui.symbols.default = '>>>'
```

This would replace the `?` by `>>>` for every CLI thing.

**Comment by derhuerst** [comment]
Hm, I'm not sure about this. I feel like it's a bad idea to even _allow_ arbitrary module to monkey path the visual style of all rendered ui elements.

There's also more problems: What if the new symbol get's stored in `ui.symbols` once a prompt has already been rendered? The next one will be rendered differently then.

For further discussions on this, please open an issue over at `cli-styles`. 😉

**Comment by nschoe** [comment]
Okay, well it's a bit sad, but I understand. I don't _really_ need it for now, so I'll let this one :-)
